### ISSUE TITLE
Crash on selecting BetterEnchantedBooks with newer versions of Cloth Config

### ISSUE THREAD

**Issue by NeRdTheNed** [Bernasss12/BetterEnchantedBooks#10]
java.lang.NoSuchMethodError: 'me.shedaniel.clothconfig2.api.ConfigCategory me.shedaniel.clothconfig2.api.ConfigBuilder.getOrCreateCategory(java.lang.String)'
    at Not Enough Crashes deobfuscated stack trace.(1.16.1+build.9)
    at dev.bernasss12.bebooks.client.gui.BEBooksConfig.getConfigScreen(BEBooksConfig.java:177)
    at dev.bernasss12.bebooks.ModMenuIntegration.lambda$getModConfigScreenFactory$0(ModMenuIntegration.java:18)
    at io.github.prospector.modmenu.ModMenu.hasConfigScreenFactory(ModMenu.java:40)
    at io.github.prospector.modmenu.gui.ModsScreen$1.render(ModsScreen.java:108)
    at net.minecraft.client.gui.screen.Screen.render(Screen:81)
    at io.github.prospector.modmenu.gui.ModsScreen.render(ModsScreen.java:233)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:603)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1021)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:654)
    at net.minecraft.client.main.Main.main(Main:215)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:564)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:564)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

This is probably due to cloth config now using a Minecraft translatable string, replacing the previous usage of just a java String.

**Comment by Bernasss12** [comment]
What version of Minecraft are you using?
Edit: Sorry for the late reply.

**Comment by NeRdTheNed** [comment]
no problems! I'm using 1.16.1, with a mod version of 1.0.1, and a Cloth Config version of 4.5.6. I can reproduce this crash by selecting BEB in Modmenu.

**Comment by Bernasss12** [comment]
Ok the mod is currently being worked on for 1.16.1 but it is not yet supported so this crash isn't a bug, it's just not meant to be compatible. I am planning to release the mod to 1.16 soon tho so stay tuned
