### ISSUE TITLE
[Bug] Configs do not stay created

### ISSUE THREAD

**Issue by itsdinkd** [Bernasss12/BetterEnchantedBooks#47]
Huge error when launching and looking at latest.log, the configs get corrupted or deleted or something. 

I can open a 'config' in game via modmenu, however, it looks like the files do not actually save in the config folder.

this is the latest log upon launching any number of times after configuring in game

[18:14:43] [Render thread/ERROR]: Failed to read config file!
java.nio.file.NoSuchFileException: D:\minecraftmods\Instances\Another Quality Modpack 2 (1)\config\bebooks\config.properties
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.52) ~[?:?]
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:375) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:426) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420) ~[?:?]
	at java.nio.file.Files.newInputStream(Files.java:160) ~[?:?]
	at java.nio.file.Files.newBufferedReader(Files.java:2916) ~[?:?]
	at java.nio.file.Files.newBufferedReader(Files.java:2948) ~[?:?]
	at dev.bernasss12.bebooks.client.gui.ModConfig.loadAndPopulateConfig(ModConfig.java:119) ~[better-enchanted-books-1.17-1.2.10.jar:?]
	at net.minecraft.client.gui.screen.TitleScreen.handler$ghg00b$init(TitleScreen:3020) ~[?:?]
	at net.minecraft.client.gui.screen.TitleScreen.init(TitleScreen) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.init(Screen:387) ~[?:?]
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient:984) ~[?:?]
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:635) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:179) [intermediary-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[18:14:43] [Render thread/ERROR]: Couldn't load enchantment data!
java.nio.file.NoSuchFileException: D:\minecraftmods\Instances\Another Quality Modpack 2 (1)\config\bebooks\enchantment_data.json
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.52) ~[?:?]
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:375) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:426) ~[?:?]
	at java.nio.file.Files.readAllBytes(Files.java:3272) ~[?:?]
	at java.nio.file.Files.readString(Files.java:3350) ~[?:?]
	at java.nio.file.Files.readString(Files.java:3309) ~[?:?]
	at dev.bernasss12.bebooks.client.gui.ModConfig.loadEnchantmentData(ModConfig.java:76) ~[better-enchanted-books-1.17-1.2.10.jar:?]
	at dev.bernasss12.bebooks.client.gui.ModConfig.loadAndPopulateConfig(ModConfig.java:169) ~[better-enchanted-books-1.17-1.2.10.jar:?]
	at net.minecraft.client.gui.screen.TitleScreen.handler$ghg00b$init(TitleScreen:3020) ~[?:?]
	at net.minecraft.client.gui.screen.TitleScreen.init(TitleScreen) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.init(Screen:387) ~[?:?]
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient:984) ~[?:?]
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:635) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:179) [intermediary-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[18:14:43] [Render thread/ERROR]: Couldn't save config file!
java.nio.file.NoSuchFileException: D:\minecraftmods\Instances\Another Quality Modpack 2 (1)\config\bebooks\config.properties
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.52) ~[?:?]
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478) ~[?:?]
	at java.nio.file.Files.newOutputStream(Files.java:224) ~[?:?]
	at java.nio.file.Files.newBufferedWriter(Files.java:2997) ~[?:?]
	at java.nio.file.Files.newBufferedWriter(Files.java:3040) ~[?:?]
	at dev.bernasss12.bebooks.client.gui.ModConfig.saveConfig(ModConfig.java:179) ~[better-enchanted-books-1.17-1.2.10.jar:?]
	at net.minecraft.client.gui.screen.TitleScreen.handler$ghg00b$init(TitleScreen:3021) ~[?:?]
	at net.minecraft.client.gui.screen.TitleScreen.init(TitleScreen) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.init(Screen:387) ~[?:?]
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient:984) ~[?:?]
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:635) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:179) [intermediary-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[18:14:43] [Render thread/ERROR]: Couldn't save enchantment data!
java.nio.file.NoSuchFileException: D:\minecraftmods\Instances\Another Quality Modpack 2 (1)\config\bebooks\enchantment_data.json
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.52) ~[?:?]
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478) ~[?:?]
	at java.nio.file.Files.newOutputStream(Files.java:224) ~[?:?]
	at java.nio.file.Files.write(Files.java:3491) ~[?:?]
	at java.nio.file.Files.writeString(Files.java:3707) ~[?:?]
	at java.nio.file.Files.writeString(Files.java:3647) ~[?:?]
	at dev.bernasss12.bebooks.client.gui.ModConfig.saveEnchantmentData(ModConfig.java:107) ~[better-enchanted-books-1.17-1.2.10.jar:?]
	at dev.bernasss12.bebooks.client.gui.ModConfig.saveConfig(ModConfig.java:200) ~[better-enchanted-books-1.17-1.2.10.jar:?]
	at net.minecraft.client.gui.screen.TitleScreen.handler$ghg00b$init(TitleScreen:3021) ~[?:?]
	at net.minecraft.client.gui.screen.TitleScreen.init(TitleScreen) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.init(Screen:387) ~[?:?]
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient:984) ~[?:?]
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:635) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:179) [intermediary-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]

**Comment by Bernasss12** [comment]
I'm sorry about this but it should be already fixed I just forgot to release the latest version on CF.
Check #44

**Comment by itsdinkd** [comment]
@Bernasss12 No worries, understandable. Any way I can get a download link to the latest version? I'm trying to upload my biggest version of my modpack and waiting for this release so everything is stable with the version.

**Comment by red2blue** [comment]
I tried to build it myself


```
> Task :compileJava
D:\minecraftmods\BetterEnchantedBooks\src\main\java\dev\bernasss12\bebooks\mixin\ItemStackMixin.java:54: warning: Cannot find target method for @Inject in net.minecraft.item.ItemStack
    @Inject(at = @At(value = "HEAD"), method = "method_17869(Ljava/util/List;Lnet/minecraft/nbt/CompoundTag;Lnet/minecraft/enchantment/Enchantment;)V")
    ^
D:\minecraftmods\BetterEnchantedBooks\src\main\java\dev\bernasss12\bebooks\mixin\ItemStackMixin.java:63: warning: Cannot find target method for @Inject in net.minecraft.item.ItemStack
    @Inject(at = @At(value = "TAIL"), method = "method_17869(Ljava/util/List;Lnet/minecraft/nbt/CompoundTag;Lnet/minecraft/enchantment/Enchantment;)V")
    ^
```

**Comment by Bernasss12** [comment]
Uploading right now. Should be up in a couple of minutes

**Comment by itsdinkd** [comment]
thanks
